name: ounass-app

image:
  repository: "swapnilkhedekar/ounass"
  tag: "1.0-linux-amd64"
  pullPolicy: Always

replicaCount: 3
revisionHistoryLimit: 3
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50


healthCheck:
  httpGet:
    path: /health
    port: 8000
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 20
